name: Deploy to Home Server

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

# Define global variables
env:
  DOCKER_IMAGE_NAME: idrisfallout/perfume_recommender_system
  DOCKER_IMAGE_TAG: "1.0"

jobs:
  build_raspberrypi:
    runs-on: raspberrypi  # Build and deploy on Raspberry Pi
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image for Raspberry Pi
        run: |
          # Build the Docker image for the native platform (Raspberry Pi)
          docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} .
          echo 'Docker image built for Raspberry Pi'

      - name: Deploy with Docker Compose to Raspberry Pi
        run: |
          docker-compose up -d
        env:
          HOME: ${{ env.HOME }}

      - name: Remove dangling Docker images
        run: |
          docker image prune -f

  build_desktop_tler9ha:
    runs-on: desktop-tler9ha  # Build and deploy on Desktop (tler9ha)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image for Desktop
        run: |
          # Build the Docker image for the native platform (Desktop)
          docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} .
          echo 'Docker image built for Desktop'

      - name: Set environment variables for Desktop
        run: |
          echo "HOME=${env:USERPROFILE}" | Out-File -Append -FilePath $env:GITHUB_ENV
        shell: powershell

      - name: Deploy with Docker Compose to Desktop
        run: |
          docker-compose up -d
        env:
          HOME: ${{ env.HOME }}

      - name: Remove dangling Docker images
        run: |
          docker image prune -f
